### ISSUE TITLE
Bug: Cannot move when crate is on top of character

### ISSUE THREAD

**Issue by ZenPylon** [PopeScooby/TreasureHunters#6]
### Summary
I can move the crate from different angles, but when the crate is directly on top of me, I can no longer move and I have to retry the level. See below (from level 5):

![Screen Recording 2022-09-15 at 6 55 59 PM](https://user-images.githubusercontent.com/1970004/190528699-a8538384-17f6-4d1b-8b30-f082994b44d7.gif)

**Comment by PopeScooby** [comment]
I have an idea for how to fix this. I'll give it a try

**Comment by PopeScooby** [comment]
it worked, this is fixed.
