### ISSUE TITLE
Bug: Slug doesn't change directions when hitting wall

### ISSUE THREAD

**Issue by ZenPylon** [PopeScooby/TreasureHunters#7]
### Summary

Noticed a minor bug in level 6, where the slug keeps slithering to the right, even though it's hitting a wall. See below:

![Screen Recording 2022-09-16 at 10 29 56 AM](https://user-images.githubusercontent.com/1970004/190676205-0d0ae2b3-03b8-4fd4-9bd9-fd465838ca33.gif)

**Comment by PopeScooby** [comment]
it will turn around eventually. Maybe I should shorten the time it runs into the wall for. it takes about 5  seconds for him to turn around right now.

**Comment by PopeScooby** [comment]
Shortened to 1 second
