### ISSUE TITLE
Calibrate repeat damage duration

### ISSUE THREAD

**Issue by ZenPylon** [PopeScooby/TreasureHunters#9]
### Summary

When landing on spikes, the time between landing and taking damage and the second (or third) "hit" from staying on the spikes too long is pretty fast, IMO

**Comment by PopeScooby** [comment]
in Scenes/Triggers/Spike_Trigger there is a node called Timer_Damage that controls that. It's currently set at .75 seconds. feel free to play around with it to find what you think is right
